from django.urls import path
from mcqmind import views

urlpatterns = [
    path('', views.MainPage),
    path('homepage/', views.HomePage),
    path('adminpage/', views.AdminPage),
    path('loginadminpage/', views.LoginAdminPage),
    path('registerpage/', views.RegisterPage),
    path('loginuserpage/', views.LoginUserPage),
    path('viewuserpage/', views.ViewUserPage),
    path('updateUserpage/', views.UpdateUserPage),
    path('deleteuserpage/', views.DeleteUserPage),
    path('cruduserpage/', views.CrudUserPage),
    path('addquestionpage/', views.AddquestionPage),
    path('updatequespage/', views.UpdateQuesPage),
    path('crudQuespage/', views.CrudQuesPage),

    path('home/', views.Home),
    path('addstudent/', views.AddUser),
    path('viewstudent/', views.ViewUser),
    path('updateUser/', views.UpdateUser),
    path('deleteuser/', views.DeleteUser),
    path('crudAddUser/', views.CrudAddUser),
    path('crudViewUser/', views.CrudViewUser),
    path('crudUpdateUser/', views.CrudUpdateUser),
    path('crudDeleteUser/', views.CrudDeleteUser),
    path('showallUSer/', views.ShowallUSer),
    path('addquestion/', views.Addquestion),
    path('showallquestions/', views.ShowallQuestions),
    path('deleteque/', views.DeleteQue),
    path('updateques/', views.UpdateQues),
    path('loginuser/', views.LoginUser),
    path('crudaddque/', views.CrudAddque),
    path('crudupdateques/', views.CrudUpdateQues),
    path('cruddeleteque/', views.CrudDeleteQue),
    path('crudviewque/', views.CrudViewQue),
    path('logoutuser/', views.LogoutUser),
    path('starttest/', views.StartTest),
    path('nextquestion/', views.NextQuestion),
    path('previousquestion/', views.PreviousQuestion),
    path('endtest/', views.EndTest),
    path('showalluserresult/', views.ShowallUserResult),
    path('logoutadmin/', views.LogoutAdmin),
    path('loginadmin/', views.LoginAdmin),
    path('showuserresults/', views.ShowUserResult),
    path('quesop/', views.QuesOp),
    path('studop/', views.StudOp),
    path('resultop/', views.ResultOp),
]