# Generated by Django 6.0.5 on 2026-06-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("qid", models.AutoField(primary_key=True, serialize=False)),
                ("qtext", models.CharField(max_length=300)),
                ("qoption1", models.CharField(max_length=300)),
                ("qoption2", models.CharField(max_length=300)),
                ("qoption3", models.CharField(max_length=300)),
                ("qoption4", models.CharField(max_length=300)),
                ("correct_answer", models.CharField(max_length=300)),
                ("subject", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="Student_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=300)),
                ("mobile_no", models.BigIntegerField()),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
