# Generated by Django 6.0.5 on 2026-06-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcqmind", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_info",
            name="id",
        ),
        migrations.AlterField(
            model_name="student_info",
            name="username",
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
