# Generated by Django 6.0.5 on 2026-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcqmind", "0003_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adminname", models.CharField(max_length=300, unique=True)),
                ("adminpassword", models.CharField(max_length=300)),
                ("adminemail", models.EmailField(max_length=254, unique=True)),
                ("adminmobile_no", models.BigIntegerField()),
            ],
            options={
                "db_table": "admins",
            },
        ),
    ]
